global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'triton'
    static_configs:
      - targets: ['host.docker.internal:8002']

  - job_name: 'preprocess_service'
    static_configs:
      - targets: ['host.docker.internal:8500']
